spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud2022?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: goods-provider
logging:
  level:
    root: INFO
info.app.name: provider
info.company.name: Ckp
info.author.name: demo