spring:
  application:
    name: fallback
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true