spring:
  application:
    name: feign-consumer
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    prefer-ip-address: true